package com.zju.mapper;

import com.zju.object.UserInfoDo;

public interface UserInfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Jul 14 11:49:19 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Jul 14 11:49:19 CST 2019
     */
    int insert(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Jul 14 11:49:19 CST 2019
     */
    int insertSelective(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Jul 14 11:49:19 CST 2019
     */
    UserInfoDo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Jul 14 11:49:19 CST 2019
     */
    int updateByPrimaryKeySelective(UserInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Sun Jul 14 11:49:19 CST 2019
     */
    int updateByPrimaryKey(UserInfoDo record);
}